#! /bin/sh

id=$(docker image ls | awk '{ if($1=="epp-restapi") print $3 }')

docker tag ${id} jamesstevens/epp-restapi
docker push jamesstevens/epp-restapi

ver="$1"
if test -z "${ver}"; then ver="$(date +%Y-%m-%d)"; fi

if test "$1"
	then
		docker tag ${id} jamesstevens/epp-restapi:${1}
		docker push jamesstevens/epp-restapi:${1}
	fi
