#! /bin/sh
# (c) Copyright 2019-2020, James Stevens ... see LICENSE for details
# Alternative license arrangements possible, contact me for more information

opts="daemon off;"
conf="nginx_ssl.conf"

exec /usr/sbin/nginx -c /etc/nginx/${conf} -g "${opts}"
